# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

description: "A multi-agent system implemented with CrewAI created to support coding activities"
settings:
  requires_data_ingestion: false
  deployment_targets: ["agent_engine", "cloud_run"]
  extra_dependencies: [
    "langchain-google-vertexai~=2.0.7",
    "langchain~=0.3.14",
    "langchain-community~=0.3.17", 
    "langchain-openai~=0.3.5",
    "langgraph~=0.2.63",
    "crewai~=0.102.0"
  ]
